sonar.projectKey=tredy-ai_prisma2go
sonar.projectName=Tredy AI Prisma2Go
sonar.sourceEncoding=UTF-8

sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out

sonar.qualitygate.wait=true
