package generator

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/tredy-ai/prisma2go/internal/config"
)

func TestGenerate(t *testing.T) {
	tests := []struct {
		name           string
		inputFile      string
		configModifier func(*config.Config)
		mustContain    []string
		mustNotContain []string
	}{
		{
			name:      "basic schema with enums and relations",
			inputFile: "../testdata/basic/input.json",
			mustContain: []string{
				"package models",
				"Code generated by prisma2go",
				"type Role int",
				"RoleAdmin Role = iota",
				"RoleUser",
				"type User struct",
				"type Post struct",
				"represents the users table",
				`db:"id"`,
				`db:"created_at"`,
				`db:"author_id"`,
				`json:"email"`,
				`json:"name,omitempty"`,
				"*string",
				"time.Time",
				"[]Post",
				"*User",
				`db:"-"`,
			},
		},
		{
			name:      "complex schema with UUIDs and multiple enums",
			inputFile: "../testdata/complex/input.json",
			mustContain: []string{
				"type Status int",
				"type Priority int",
				"StatusDraft Status = iota",
				"PriorityLow Priority = iota",
				"uuid.UUID",
				"json.RawMessage",
				"int64",
				"[]string",
				"*Priority",
				"type Organization struct",
				"type Project struct",
				"type Task struct",
				"type Member struct",
				`"github.com/google/uuid"`,
				`"encoding/json"`,
			},
		},
		{
			name:      "no json tags",
			inputFile: "../testdata/basic/input.json",
			configModifier: func(cfg *config.Config) {
				cfg.JSONTags = false
			},
			mustNotContain: []string{
				`json:"email"`,
				`json:"name"`,
			},
		},
		{
			name:      "no db tags",
			inputFile: "../testdata/basic/input.json",
			configModifier: func(cfg *config.Config) {
				cfg.DBTags = false
			},
			mustNotContain: []string{
				`db:"email"`,
				`db:"name"`,
			},
		},
		{
			name:      "no tags at all",
			inputFile: "../testdata/basic/input.json",
			configModifier: func(cfg *config.Config) {
				cfg.JSONTags = false
				cfg.DBTags = false
			},
			mustNotContain: []string{
				`json:"email"`,
				`db:"email"`,
			},
		},
		{
			name:      "uuid as string when package empty",
			inputFile: "../testdata/complex/input.json",
			configModifier: func(cfg *config.Config) {
				cfg.UUIDPackage = ""
			},
			mustNotContain: []string{
				"uuid.UUID",
				`"github.com/google/uuid"`,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			outputFile := filepath.Join(tmpDir, "models.go")

			cfg := config.DefaultConfig()
			cfg.Input = tt.inputFile
			cfg.Output = outputFile
			cfg.Package = "models"
			cfg.NoEnumer = true

			if tt.configModifier != nil {
				tt.configModifier(cfg)
			}

			gen := New(cfg)
			err := gen.Run()
			require.NoError(t, err, "generation should succeed")

			output, err := os.ReadFile(outputFile)
			require.NoError(t, err, "should read output file")

			content := string(output)

			for _, expected := range tt.mustContain {
				assert.Contains(t, content, expected, "output should contain %q", expected)
			}

			for _, notExpected := range tt.mustNotContain {
				assert.NotContains(t, content, notExpected, "output should not contain %q", notExpected)
			}
		})
	}
}

func TestGenerateCompiles(t *testing.T) {
	tests := []struct {
		name      string
		inputFile string
	}{
		{"basic schema", "../testdata/basic/input.json"},
		{"complex schema", "../testdata/complex/input.json"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tmpDir := t.TempDir()
			outputFile := filepath.Join(tmpDir, "models.go")

			cfg := config.DefaultConfig()
			cfg.Input = tt.inputFile
			cfg.Output = outputFile
			cfg.Package = "models"
			cfg.NoEnumer = true

			gen := New(cfg)
			err := gen.Run()
			require.NoError(t, err)

			output, err := os.ReadFile(outputFile)
			require.NoError(t, err)

			content := string(output)

			// Basic validity checks - the code should at least have proper structure
			assert.True(t, strings.HasPrefix(content, "// Code generated by prisma2go"))
			assert.Contains(t, content, "package models")
		})
	}
}

func TestGenerateMultilineDocComments(t *testing.T) {
	tmpDir := t.TempDir()
	inputFile := filepath.Join(tmpDir, "input.json")
	outputFile := filepath.Join(tmpDir, "models.go")

	schema := `{
  "enums": [],
  "models": [
    {
      "name": "departments",
      "dbName": null,
      "documentation": "Replaces the former chain.\nA department is always a flat child\nand owns exactly one workspace.",
      "fields": [
        { "name": "id", "kind": "scalar", "type": "Int", "isId": true, "isRequired": true, "isList": false, "documentation": "Primary identifier.\nNever reused." }
      ]
    }
  ]
}`
	require.NoError(t, os.WriteFile(inputFile, []byte(schema), 0644))

	cfg := config.DefaultConfig()
	cfg.Input = inputFile
	cfg.Output = outputFile
	cfg.Package = "models"
	cfg.NoEnumer = true

	require.NoError(t, New(cfg).Run())

	output, err := os.ReadFile(outputFile)
	require.NoError(t, err)

	_, err = parser.ParseFile(token.NewFileSet(), "models.go", output, parser.ParseComments)
	require.NoError(t, err, "generated code must parse:\n%s", output)

	for _, line := range []string{
		"A department is always a flat child",
		"and owns exactly one workspace.",
		"Never reused.",
	} {
		assert.Regexp(t, `(?m)^\s*// `+regexp.QuoteMeta(line)+`$`, string(output))
	}
}
